CREATE TABLE medication (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    dosage_amount NUMERIC(10, 2) NOT NULL,
    dosage_unit VARCHAR(20) NOT NULL,
    administration_route VARCHAR(30) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    low_stock_threshold INTEGER NOT NULL,
    expiration_date DATE NOT NULL,
    active BOOLEAN NOT NULL,
    inventory_id INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_medication_stock_non_negative CHECK (stock_quantity >= 0),
    CONSTRAINT chk_medication_low_stock_threshold_non_negative CHECK (low_stock_threshold >= 0)
);

CREATE TABLE medication_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE medication
    ADD CONSTRAINT fk_medication_inventory
    FOREIGN KEY (inventory_id) REFERENCES medication_inventory(id);

CREATE TABLE medication_schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    patient_id BIGINT NOT NULL,
    frequency_type VARCHAR(30) NOT NULL,
    times_per_day INTEGER NOT NULL,
    administration_time TIME NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_medication_schedule_medication
        FOREIGN KEY (medication_id) REFERENCES medication(id)
);

CREATE TABLE dose_administration (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    schedule_id INTEGER NOT NULL,
    patient_id BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(250),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_dose_administration_medication
        FOREIGN KEY (medication_id) REFERENCES medication(id),
    CONSTRAINT fk_dose_administration_schedule
        FOREIGN KEY (schedule_id) REFERENCES medication_schedule(id)
);

CREATE TABLE clinical_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    medication_id INTEGER,
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_clinical_log_medication
        FOREIGN KEY (medication_id) REFERENCES medication(id)
);

CREATE TABLE replenishment_alert (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    patient_id BIGINT NOT NULL,
    current_stock INTEGER NOT NULL,
    resolved BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_replenishment_alert_medication
        FOREIGN KEY (medication_id) REFERENCES medication(id)
);

CREATE INDEX idx_medication_patient_id ON medication(patient_id);
CREATE INDEX idx_medication_active_patient_id ON medication(patient_id, active);
CREATE INDEX idx_medication_schedule_patient_active ON medication_schedule(patient_id, active);
CREATE INDEX idx_dose_administration_medication_occurred_at ON dose_administration(medication_id, occurred_at DESC);
CREATE INDEX idx_clinical_log_patient_created_at ON clinical_log(patient_id, created_at DESC);
CREATE INDEX idx_replenishment_alert_patient_resolved ON replenishment_alert(patient_id, resolved);
