FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=build /workspace/target/*-SNAPSHOT.jar app.jar

EXPOSE 8087
ENTRYPOINT ["java", "-jar", "app.jar"]
